$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $PSScriptRoot
$session = (cmd /c agent-browser session id --scope worktree --prefix eagle-ui-final).Trim()
cmd /c agent-browser --session $session open about:blank | Out-Null

$fab = Get-Content -Raw (Join-Path $root 'eagle-web-collector.user.js')
$fabStart = $fab.IndexOf('style.textContent = `') + 'style.textContent = `'.Length
$fabEnd = $fab.IndexOf('`;', $fabStart)
$fabCss = $fab.Substring($fabStart, $fabEnd - $fabStart)

$x = Get-Content -Raw (Join-Path $root 'eagle-x-collector.user.js')
$xStart = $x.IndexOf('css: `') + 'css: `'.Length
$xEnd = $x.IndexOf('`,', $xStart)
$xCss = $x.Substring($xStart, $xEnd - $xStart)

$html = @"
<!doctype html><meta charset='utf-8'><style>
body{margin:0;background:#f2f3f5;font-family:Segoe UI,system-ui,sans-serif;min-height:100vh}.preview-title{position:fixed;left:20px;top:10px;color:#475569;font-size:13px;z-index:20}.preview-note{position:fixed;right:20px;top:10px;color:#64748b;font-size:12px;z-index:20}#eagle-scraper-panel{position:absolute!important;top:48px!important;left:24px!important;right:auto!important;transform:none!important}.tmd-batch-launcher{display:none!important}.tmd-batch-panel{position:absolute!important;top:48px!important;right:24px!important;transform:none!important;opacity:1!important;visibility:visible!important;pointer-events:auto!important}.tmd-batch-panel>*{position:relative;z-index:1}.esp-tag-select-wrap.open .esp-tag-menu,.esp-folder-select-wrap.open .esp-folder-menu{display:flex!important;flex-direction:column!important}.tmd-batch-picker.is-open .tmd-batch-picker-menu{display:flex!important}.esp-folder-option-checkbox,.tmd-batch-folder-checkbox{display:inline-flex!important}.esp-folder-option-icon,.tmd-batch-folder-icon{display:inline-flex!important}
$fabCss
$xCss
</style><div class='preview-title'>本地 UI 预览：Fab / X 统一选择交互</div><div class='preview-note'>仅验证布局，不连接 Eagle 或 X</div>
<div id='eagle-scraper-panel' class='expanded'>
<div class='esp-header'><div><div class='esp-header-title'><span class='esp-header-icon'>◈</span><span>Eagle 批量采集</span></div><div class='esp-header-site-row'><div class='esp-header-site'>Fab · 商品详情</div><div class='esp-connection-status is-connected'><span class='esp-connection-dot'></span><span>已连接</span></div></div></div><span class='esp-toggle'>▲</span></div>
<div class='esp-body'><div class='esp-body-content'><div class='esp-mode-card'><div class='esp-label'>保存方式</div><div class='esp-mode-grid'><button class='esp-mode-btn active'><span class='esp-mode-btn-title'>保存到 Eagle</span></button><button class='esp-mode-btn'><span class='esp-mode-btn-title'>本地下载</span></button></div></div>
<div class='esp-folder'><div class='esp-label'>目标文件夹（可多选）</div><div class='esp-folder-select-wrap open'><button class='esp-folder-trigger'><span class='esp-folder-trigger-text'>2 个文件夹</span><span class='esp-folder-trigger-icon'>⌃</span></button><div class='esp-folder-menu'><div class='esp-picker-head'><input class='esp-folder-search' placeholder='搜索文件夹...'><span class='esp-picker-mode'>选择目标</span></div><div class='esp-folder-recent has-items'><button class='esp-recent-chip'>最近：2 个文件夹</button></div><div class='esp-folder-tree'><button class='esp-folder-option active'><span class='esp-folder-option-spacer'></span><span class='esp-folder-option-label'>Eagle丨成长</span><span class='esp-folder-option-check'>✓</span></button><button class='esp-folder-option'><span class='esp-folder-option-toggle expanded'>›</span><span class='esp-folder-option-label'>01. 学习教程</span></button><button class='esp-folder-option' style='padding-left:34px'><span class='esp-folder-option-spacer'></span><span class='esp-folder-option-label'>01. 三维CG</span><span class='esp-folder-option-check'>✓</span></button><button class='esp-folder-option active' style='padding-left:48px'><span class='esp-folder-option-spacer'></span><span class='esp-folder-option-label'>01. 行业信息</span></button></div><div class='esp-picker-footer'><span>可多选文件夹</span><button class='esp-picker-done'>完成</button><span>Esc 关闭</span></div></div></div></div>
<div class='esp-folder'><div class='esp-label'>标签</div><div class='esp-tag-select-wrap open'><button class='esp-tag-trigger'><span>Fab、参考</span><span class='esp-tag-trigger-meta'>2 个已选</span></button><div class='esp-tag-menu'><div class='esp-picker-head'><input class='esp-tag-search' placeholder='搜索标签...'><span class='esp-picker-mode'>可多选</span></div><div class='esp-tag-recent has-items'><button class='esp-recent-chip'>最近：Fab</button><button class='esp-recent-chip'>参考</button></div><div class='esp-tag-list'><button class='esp-tag-option active'><span class='esp-tag-option-check'>✓</span><span class='esp-tag-option-label'>Fab</span></button><button class='esp-tag-option active'><span class='esp-tag-option-check'>✓</span><span class='esp-tag-option-label'>参考</span></button><button class='esp-tag-option'><span class='esp-tag-option-check'></span><span class='esp-tag-option-label'>设计</span></button><button class='esp-tag-option'><span class='esp-tag-option-check'></span><span class='esp-tag-option-label'>photo</span></button></div><div class='esp-tag-manual'><textarea class='esp-textarea' placeholder='手动输入标签，用逗号或换行分隔'></textarea></div><div class='esp-picker-footer'><span>点击切换</span><span>Enter 完成</span><span>Esc 关闭</span></div></div></div></div><button class='esp-btn esp-btn-primary esp-btn-full'>开始采集</button></div></div></div>
<div class='tmd-batch-panel is-open'><div class='tmd-batch-title'>X 批量采集</div><div class='tmd-batch-status'>准备就绪</div><div class='tmd-batch-progress'>媒体 0 · 失败 0</div><div class='tmd-batch-folder'><div class='tmd-batch-folder-label'>Eagle 目标文件夹</div><div class='tmd-batch-picker is-open'><button class='tmd-batch-picker-trigger'><span>Eagle丨成长 / 01. 三维CG</span><span class='tmd-batch-picker-meta'>已选择</span></button><div class='tmd-batch-picker-menu'><div class='tmd-batch-picker-head'><input class='tmd-batch-folder-search' placeholder='搜索文件夹...'><span>选择目标</span></div><div class='tmd-batch-folder-recent has-items'><button class='tmd-batch-recent-chip'>最近：Eagle丨成长</button></div><div class='tmd-batch-folder-tree'><button class='tmd-batch-folder-node'><span class='tmd-batch-folder-toggle'>›</span><span class='tmd-batch-folder-node-label'>Eagle丨成长</span></button><button class='tmd-batch-folder-node is-selected' style='padding-left:34px'><span class='tmd-batch-folder-toggle'>•</span><span class='tmd-batch-folder-node-label'>01. 三维CG</span><span class='tmd-batch-folder-node-check'>✓</span></button><button class='tmd-batch-folder-node' style='padding-left:48px'><span class='tmd-batch-folder-toggle'>•</span><span class='tmd-batch-folder-node-label'>01. 行业信息</span></button></div><div class='tmd-batch-picker-footer'><span>↑↓ 移动</span><span>Enter 选择</span><span>Esc 关闭</span></div></div></div><button class='tmd-batch-folder-refresh'>刷新目录</button></div><div class='tmd-batch-folder tmd-batch-tags'><div class='tmd-batch-folder-label'>标签</div><div class='tmd-batch-picker'><button class='tmd-batch-picker-trigger'><span>喜欢、photo</span><span class='tmd-batch-picker-meta'>2 个已选</span></button></div></div><div class='tmd-batch-actions'><button class='tmd-batch-btn primary'>保存到 Eagle</button><button class='tmd-batch-btn'>开始下载</button></div></div>
"@
$script = 'document.open();document.write(' + ($html | ConvertTo-Json -Compress) + ');document.close();'
$scriptBase64 = [Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes($script))
cmd /c agent-browser --session $session eval -b $scriptBase64 | Out-Null
$shot = Join-Path $root '_ui_preview_20260822.png'
cmd /c agent-browser --session $session screenshot $shot
Write-Output "SESSION=$session"
Write-Output "SHOT=$shot"
